#!/bin/sh

# Source: https://github.com/ericmurphyxyz/dotfiles/blob/master/.local/bin/changebrightness

# Use brillo to logarithmically adjust laptop screen brightness
# and send a notification displaying the current brightness level after.

send_notification() {
	brightness=$(printf "%.0f\n" "$(brillo -Gq)")
	notify-send -a "changebrightness" -u low -r 9993 -h int:value:"$brightness" -i "/usr/share/icons/Adwaita/symbolic/status/display-brightness-symbolic.svg" "Brightness" "Currently at $brightness%" -t 500
}

case $1 in
up)
	brillo -A 5 -q
	send_notification "$1"
	;;
down)
	brillo -U 5 -q
	send_notification "$1"
	;;
esac
