#!/bin/sh

# Argument should be the request link to the a.m3u8 file

current_datetime=$(date +"%Y-%m-%d_%H-%M-%S")

output_filename="output_${current_datetime}.mp4"

ffmpeg -i "$1" -c copy -bsf:a aac_adtstoasc "$output_filename"
